name: Run Postman Collection

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-postman:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start containers 🐳
        run: |
          export DISABLE_LOGGING=true
          docker compose -f docker-compose.yml up -d
          
      - name: Sleep for 60 seconds
        run: sleep 60s
        shell: bash
        
      - name: Create & Seed database 🌱
        run: |
          docker compose exec -T laravel-api php artisan migrate:refresh --seed

      - name: GET Version
        run: curl -v -X GET 'http://localhost:8091/status'

      - name: GET resource
        run: curl -v -X GET 'http://localhost:8091/products?between=price,1&page=1'

      - name: POST login
        run: |
          curl -v -X POST 'http://localhost:8091/users/login' \
          -H 'Content-Type: application/json' \
          --data-raw '{"email":"customer@practicesoftwaretesting.com","password":"welcome01"}'

      - name: Install Newman
        run: npm install -g newman
      
      - name: Run Postman Collection Product with Newman
        run: newman run ./tests/collections/Product.postman_collection.json --env-var "BASE_URL=${{ secrets.BASE_URL }}" --iteration-data ./tests/data/data_product.csv

      - name: Run Postman Collection Brand with Newman
        run: newman run ./tests/collections/Brand.postman_collection.json --env-var "BASE_URL=${{ secrets.BASE_URL }}" --iteration-data ./tests/data/data_brand.csv
